# Generated by Django 6.0.7 on 2026-07-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='미션 제목')),
                ('description', models.TextField(verbose_name='미션 설명')),
                ('step_guide', models.JSONField(blank=True, default=list, help_text='각 단계별 가이드 GIF를 저장합니다.', verbose_name='단계별 GIF 경로 리스트')),
                ('answer_data', models.JSONField(blank=True, default=dict, help_text='각 단계별 정답 데이터를 JSON 형식으로 저장합니다.', verbose_name='정답 데이터 세트')),
            ],
        ),
    ]
