# Generated by Django 6.0.7 on 2026-07-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='미션 제목')),
                ('description', models.TextField(verbose_name='미션 설명')),
                ('answer_data', models.JSONField(blank=True, default=dict, help_text='각 단계별 정답 데이터를 JSON 형식으로 저장합니다.', verbose_name='정답 데이터 세트')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStepView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='단계 번호 (1~5)')),
                ('guide_text', models.TextField(verbose_name='우측 가이드 설명문')),
                ('guide_image', models.ImageField(blank=True, null=True, upload_to='guides/', verbose_name='우측 가이드 GIF/이미지')),
                ('view_data', models.JSONField(blank=True, default=dict, help_text='왼쪽 배달앱 UI 렌더링에 필요한 더미 데이터를 저장합니다.', verbose_name='화면 구성 데이터')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='deliverys.mission')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('mission', 'step_number')},
            },
        ),
    ]
